#!/usr/bin/perl
# Builds data/trail-network.js — a lightweight network of real trail lines
# (from .cache/osm-network-raw.json) that js/snap-trace.js snaps against
# while you drag to trace a custom route, so the traced line follows the
# real trail shape instead of straight segments between taps.
#
# Restricted to genuine trail-type ways (footway/path/track/bridleway/
# steps) — service roads and residential streets were the vast majority of
# a broader query (5,521 of 14,149 ways were driveways/parking-lot
# "service" ways alone) and add bulk without helping a hiking app.
#
# Each way is thinned with a simple perpendicular-distance filter so
# nearly-collinear points don't bloat the shipped file — trail shape is
# preserved, redundant points aren't.
#
#   perl scripts/build-trail-network.pl
use strict;
use warnings;
use JSON::PP;

my $json = JSON::PP->new;
open(my $fh, '<', '.cache/osm-network-raw.json') or die "Can't read .cache/osm-network-raw.json: $!\nRun the Overpass fetch for the network first (see README.md).\n";
local $/;
my $data = $json->decode(<$fh>);
close $fh;

my %KEEP_HIGHWAY = map { $_ => 1 } qw(footway path track bridleway steps);

# Perpendicular distance from point p to the line through a-b, in degrees.
sub perp_dist {
  my ($p, $a, $b) = @_;
  my ($dx, $dy) = ($b->[0] - $a->[0], $b->[1] - $a->[1]);
  my $len = sqrt($dx*$dx + $dy*$dy);
  return sqrt(($p->[0]-$a->[0])**2 + ($p->[1]-$a->[1])**2) if $len == 0;
  my $t = (($p->[0]-$a->[0])*$dx + ($p->[1]-$a->[1])*$dy) / ($len*$len);
  my ($projx, $projy) = ($a->[0] + $t*$dx, $a->[1] + $t*$dy);
  return sqrt(($p->[0]-$projx)**2 + ($p->[1]-$projy)**2);
}

# Simple recursive Douglas-Peucker simplification.
my $TOLERANCE_DEG = 0.00003; # ~3m — trims redundant points, keeps trail shape
sub simplify {
  my ($pts) = @_;
  return $pts if @$pts <= 2;
  my ($maxDist, $maxIdx) = (0, 0);
  for my $i (1 .. $#$pts - 1) {
    my $d = perp_dist($pts->[$i], $pts->[0], $pts->[-1]);
    if ($d > $maxDist) { $maxDist = $d; $maxIdx = $i; }
  }
  if ($maxDist > $TOLERANCE_DEG) {
    my $left = simplify([@{$pts}[0 .. $maxIdx]]);
    my $right = simplify([@{$pts}[$maxIdx .. $#$pts]]);
    pop @$left;
    return [@$left, @$right];
  }
  return [$pts->[0], $pts->[-1]];
}

my @network;
my ($totalRaw, $totalSimplified) = (0, 0);
for my $el (@{$data->{elements}}) {
  next unless $el->{type} eq 'way';
  my $hw = $el->{tags}{highway} // '';
  next unless $KEEP_HIGHWAY{$hw};
  my @pts = map { [sprintf('%.6f', $_->{lat}) + 0, sprintf('%.6f', $_->{lon}) + 0] } @{$el->{geometry}};
  next unless @pts >= 2;
  $totalRaw += scalar(@pts);
  my $simplified = simplify(\@pts);
  $totalSimplified += scalar(@$simplified);
  push @network, $simplified;
}

open(my $out, '>', 'data/trail-network.js') or die "Can't write data/trail-network.js: $!";
print $out "// Real trail-line network for drag-to-trace snapping (js/snap-trace.js).\n";
print $out "// Generated by scripts/build-trail-network.pl from OpenStreetMap data — do not hand-edit.\n";
print $out "const TRAIL_NETWORK = " . $json->encode(\@network) . ";\n";
close $out;

printf STDERR "Wrote data/trail-network.js: %d ways, %d points (simplified from %d, %.0f%% reduction)\n",
  scalar(@network), $totalSimplified, $totalRaw, 100 * (1 - $totalSimplified / ($totalRaw || 1));
