#!/usr/bin/perl
# Combines data/trails-metadata.json (hand-curated: name, difficulty, blurb,
# address, elevation) with data/trails-geometry.json (real OSM-derived paths,
# from build-trail-geometry.pl) into data/trails.js — the plain JS data file
# the app loads via <script src="data/trails.js">.
#
#   perl scripts/merge-trail-data.pl
use strict;
use warnings;
use JSON::PP;

my $json = JSON::PP->new->utf8->canonical;

sub read_json_file {
  my ($path) = @_;
  open(my $fh, '<', $path) or die "Can't read $path: $!";
  local $/;
  return $json->decode(<$fh>);
}

sub haversine_miles {
  my ($a, $b) = @_;
  my $R = 3958.8;
  my $dlat = ($b->[0] - $a->[0]) * 3.14159265358979 / 180;
  my $dlon = ($b->[1] - $a->[1]) * 3.14159265358979 / 180;
  my $rlat1 = $a->[0] * 3.14159265358979 / 180;
  my $rlat2 = $b->[0] * 3.14159265358979 / 180;
  my $h = sin($dlat/2)**2 + cos($rlat1) * cos($rlat2) * sin($dlon/2)**2;
  return 2 * $R * atan2(sqrt($h), sqrt(1 - $h));
}

my $metadata = read_json_file('data/trails-metadata.json');
my $geometry = read_json_file('data/trails-geometry.json');

my @trails;
for my $m (@{$metadata->{trails}}) {
  my $id = $m->{id};
  my $g = $geometry->{$id};
  die "No geometry found for $id — run scripts/build-trail-geometry.pl first\n" unless $g && @{$g->{path}};

  my @path = @{$g->{path}};
  my $oneWayMiles = haversine_miles($path[0], $path[-1]) == 0 ? 0 : 0; # unused, kept explicit below
  $oneWayMiles = 0;
  for my $i (1 .. $#path) { $oneWayMiles += haversine_miles($path[$i-1], $path[$i]); }

  my $type = $m->{distanceType};
  my $displayMiles = $oneWayMiles;
  if ($type eq 'out-and-back') {
    $displayMiles = $oneWayMiles * 2;
  } elsif ($type eq 'loop') {
    # Close the loop back to the start so both the drawn line and the
    # reported distance reflect one full lap, not just the traced network.
    my $closing = haversine_miles($path[-1], $path[0]);
    push @path, [@{$path[0]}];
    $displayMiles = $oneWayMiles + $closing;
  }

  my $distanceLabel = sprintf('%.1f mi', $displayMiles);

  my @stats = ([$distanceLabel, 'Distance'], [$m->{elevation}, 'Elevation'], [$m->{difficulty}, 'Difficulty']);
  push @stats, @{$m->{extraStats}} if $m->{extraStats};

  push @trails, {
    id => $id,
    name => $m->{name},
    address => $m->{address},
    difficulty => $m->{difficulty},
    distance => $distanceLabel,
    distanceType => $type,
    elevation => $m->{elevation},
    blurb => $m->{blurb},
    trailhead => $path[0],
    path => \@path,
    stats => \@stats,
    source => {
      provider => 'OpenStreetMap (Overpass API)',
      wayIds => $g->{wayIds},
      wayCount => $g->{wayCount} + 0,
    },
  };
}

my $js = "// Real trail-line geometry sourced from OpenStreetMap via the Overpass API.\n" .
  "// Generated by scripts/merge-trail-data.pl — do not hand-edit path/trailhead here;\n" .
  "// edit data/trails-metadata.json (names, blurbs, difficulty) or\n" .
  "// data/trail-sources.json (which OSM ways to pull) and rerun the build scripts.\n" .
  "const TRAIL_DATA = " . $json->pretty->encode(\@trails) . ";\n";

open(my $out, '>', 'data/trails.js') or die "Can't write data/trails.js: $!";
print $out $js;
close $out;
printf STDERR "Wrote data/trails.js with %d trails\n", scalar(@trails);
